### ISSUE TITLE
./lib/MaskInput.js is not present in npm package

### ISSUE THREAD

**Issue by zauni** [xnimorz/vanilla-masked-input#2]
Hi @xnimorz when I install the mask-input package, the `./lib/MaskInput.js` is missing inside the package. In the package.json the "main" field is set to `./lib/MaskInput.js`
Maybe the `npm run build` was not used before publishing?

Could you please republish the package with the built MaskInput.js? Would be great :) Thanks!

**Comment by xnimorz** [comment]
Hi! republished using 1.0.3 version

**Comment by zauni** [comment]
Thank you very much! That was fast 💯
